baseURL = 'https://miwa23333.github.io/'
languageCode = 'en-us'
title = 'miwa23333'
theme = "PaperMod"

[services]
[services.googleAnalytics]
id = "G-3ZTQ7BMS2D"

[caches]
[caches.images]
dir = ":cacheDir/images"

[menus]
[[menus.main]]
name = 'About'
pageRef = '/about'
[[menus.main]]
name = 'Dodorama'
url = '/dodorama'
[[menus.main]]
name = '動漫中文填字遊戲'
url = '/animanga-crossword'
[[menus.main]]
name = 'Terms of Service'
url = '/tos'
[[menus.main]]
name = 'Privacy'
url = '/privacy'
