baseURL = 'https://miwa23333.github.io/'
languageCode = 'en-us'
title = 'miwa23333'
theme = "PaperMod"

[services]
[services.googleAnalytics]
id = "G-3ZTQ7BMS2D"

[caches]
[caches.images]
dir = ":cacheDir/images"

[menus]
[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 1
[[menus.main]]
name = 'Dodorama'
url = '/dodorama'
weight = 1
[[menus.main]]
name = '動漫中文填字遊戲'
url = '/animanga-crossword'
weight = 1
[[menus.main]]
name = 'Terms of Service'
url = '/tos'
weight = 2
[[menus.main]]
name = 'Privacy'
url = '/privacy'
weight = 3
[[menus.main]]
name = 'Contact Us'
url = '/contact-us'
weight = 4
